In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
seoul_sales=pd.read_csv("서울시 우리마을가게 상권분석서비스(상권-추정매출)_2019.csv", engine='python')
seoul_sales_2019=pd.DataFrame(seoul_sales)
seoul_sales_2019

,기준_년_코드,기준_분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,서비스_업종_코드,서비스_업종_코드_명,당월_매출_금액,당월_매출_건수,...,시간대_건수~24_매출_건수,남성_매출_건수,여성_매출_건수,연령대_10_매출_건수,연령대_20_매출_건수,연령대_30_매출_건수,연령대_40_매출_건수,연령대_50_매출_건수,연령대_60_이상_매출_건수,점포수
0,2019,4,U,관광특구,1001496,강남 마이스 관광특구,CS300043,전자상거래업,16243089,458,...,0,117,341,5,71,195,156,26,5,7
1,2019,4,U,관광특구,1001496,강남 마이스 관광특구,CS300035,인테리어,57290367,739,...,0,369,370,0,0,369,370,0,0,4
2,2019,4,U,관광특구,1001496,강남 마이스 관광특구,CS300032,가전제품,2418241704,11633,...,336,4998,5696,138,2886,3045,2122,1094,1403,8
3,2019,4,U,관광특구,1001496,강남 마이스 관광특구,CS300031,가구,9035390798,5146,...,0,2185,2749,0,105,387,1234,1445,1762,5
4,2019,4,U,관광특구,1001496,강남 마이스 관광특구,CS300028,화초,702775358,12583,...,343,7078,4510,115,3126,3837,2602,1107,798,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177225,2019,1,A,골목상권,1000001,계동길,CS100005,제과점,196276254,23278,...,1369,9568,12229,408,3952,7011,5095,3328,2002,5
177226,2019,1,A,골목상권,1000001,계동길,CS100004,양식음식점,190423119,3717,...,100,1605,1839,31,1183,769,585,653,223,5
177227,2019,1,A,골목상권,1000001,계동길,CS100003,일식음식점,66221879,1636,...,217,697,666,0,154,531,271,204,205,4
177228,2019,1,A,골목상권,1000001,계동길,CS100002,중식음식점,40472439,2154,...,32,863,1254,174,815,471,424,179,53,1
177229,2019,1,A,골목상권,1000001,계동길,CS100001,한식음식점,689554776,19850,...,333,7876,9010,50,3749,5447,3447,2541,1656,20

In [3]:
seoul_sales_2019.columns

Index(['기준_년_코드', '기준_분기_코드', '상권_구분_코드', '상권_구분_코드_명', '상권_코드', '상권_코드_명',
       '서비스_업종_코드', '서비스_업종_코드_명', '당월_매출_금액', '당월_매출_건수', '주중_매출_비율',
       '주말_매출_비율', '월요일_매출_비율', '화요일_매출_비율', '수요일_매출_비율', '목요일_매출_비율',
       '금요일_매출_비율', '토요일_매출_비율', '일요일_매출_비율', '시간대_00~06_매출_비율',
       '시간대_06~11_매출_비율', '시간대_11~14_매출_비율', '시간대_14~17_매출_비율',
       '시간대_17~21_매출_비율', '시간대_21~24_매출_비율', '남성_매출_비율', '여성_매출_비율',
       '연령대_10_매출_비율', '연령대_20_매출_비율', '연령대_30_매출_비율', '연령대_40_매출_비율',
       '연령대_50_매출_비율', '연령대_60_이상_매출_비율', '주중_매출_금액', '주말_매출_금액', '월요일_매출_금액',
       '화요일_매출_금액', '수요일_매출_금액', '목요일_매출_금액', '금요일_매출_금액', '토요일_매출_금액',
       '일요일_매출_금액', '시간대_00~06_매출_금액', '시간대_06~11_매출_금액', '시간대_11~14_매출_금액',
       '시간대_14~17_매출_금액', '시간대_17~21_매출_금액', '시간대_21~24_매출_금액', '남성_매출_금액',
       '여성_매출_금액', '연령대_10_매출_금액', '연령대_20_매출_금액', '연령대_30_매출_금액',
       '연령대_40_매출_금액', '연령대_50_매출_금액', '연령대_60_이상_매출_금액', '주중_매출_건수',
       '주말_매출_건수', '월요일_매출_건수', '화요일_매출_건수', '수요일_매출_건수', '목요일_매출_건수',
       '금요일_매출_건수', '토요일_매출_건수', '일요일_매출_건수', '시간대_건수~06_매출_건수',
       '시간대_건수~11_매출_건수', '시간대_건수~14_매출_건수', '시간대_건수~17_매출_건수',
       '시간대_건수~21_매출_건수', '시간대_건수~24_매출_건수', '남성_매출_건수', '여성_매출_건수',
       '연령대_10_매출_건수', '연령대_20_매출_건수', '연령대_30_매출_건수', '연령대_40_매출_건수',
       '연령대_50_매출_건수', '연령대_60_이상_매출_건수', '점포수'],
      dtype='object')

In [4]:
business_area=seoul_sales_2019['상권_코드_명'].unique()
print(business_area)
print(len(seoul_sales_2019['상권_코드_명'].unique()))

['강남 마이스 관광특구' '잠실 관광특구' '종로·청계 관광특구' ... '계동길' '신설종합시장' '대학14길']
1489

In [5]:
category=seoul_sales_2019['서비스_업종_코드_명'].unique()
print(category)
print(len(category))

['전자상거래업' '인테리어' '가전제품' '가구' '화초' '섬유제품' '완구' '운동/경기용품' '화장품' '문구' '의약품'
 '시계및귀금속' '안경' '가방' '신발' '일반의류' '반찬가게' '핸드폰' '컴퓨터및주변장치판매' '편의점' '슈퍼마켓'
 '피부관리실' '네일숍' '미용실' '스포츠클럽' '치과의원' '일반의원' '커피-음료' '분식전문점' '패스트푸드점' '제과점'
 '양식음식점' '일식음식점' '중식음식점' '한식음식점' '서적' '의료기기' '육류판매' '노래방' '고시원' '여관' '세탁소'
 '자동차수리' 'PC방' '골프연습장' '당구장' '한의원' '스포츠 강습' '호프-간이주점' '치킨전문점' '조명용품' '철물점'
 '애완동물' '청과상' '수산물판매' '미곡판매' '가전제품수리' '예술학원' '외국어학원' '일반교습학원' '자동차미용'
 '부동산중개업' '자전거 및 기타운송장비' '유아의류' '한복점' '볼링장' '회계사사무소' '기타법무서비스' '컴퓨터학원'
 '주류도매' '세무사사무소' '법무사사무소' '변리사사무소' '변호사사무소' '동물병원']
75

In [6]:
category_name=['가전제품', '가구', '화초', '섬유제품', '완구', '운동/경기용품', '화장품', '문구', '시계및귀금속',
               '안경', '가방', '신발', '일반의류', '반찬가게', '컴퓨터및주변장치판매', '편의점', '슈퍼마켓', '커피-음료',
               '분식전문점', '패스트푸드점', '제과점', '양식음식점', '일식음식점', '중식음식점', '한식음식점', '서적',
               '육류판매', '호프-간이주점', '치킨전문점', '조명용품', '철물점', '청과상', '수산물판매', '미곡판매',
               '유아의류', '한복점', '주류도매']
print(len(category_name))

37

In [7]:
E=seoul_sales_2019.groupby(['상권_코드_명', '서비스_업종_코드_명', '기준_분기_코드'])
category_seoul=E.sum()
category_seoul

                              기준_년_코드    상권_코드      당월_매출_금액  당월_매출_건수  \
상권_코드_명 서비스_업종_코드_명 기준_분기_코드
가락시장    미곡판매        4            2019  1001060   17784890556    280217
        반찬가게        1            2019  1001060   21668463261    354392
                    2            2019  1001060   17841577104    198941
                    3            2019  1001060   17462095928    209922
                    4            2019  1001060  242036013085   4487383
...                               ...      ...           ...       ...
흑석시장    호프-간이주점     3            2019  1001448     228207020      4522
                    4            2019  1001448     403207421      8681
        회계사사무소      1            2019  1001448      43460022       130
                    2            2019  1001448      28615704       108
                    3            2019  1001448      21210600       151

                              주중_매출_비율  주말_매출_비율  월요일_매출_비율  화요일_매출_비율  \
상권_코드_명 서비스_업종_코드_명 기준_분기_코드
가락시장    미곡판매        4               89        11         17         23
        반찬가게        1               77        23         16         15
                    2               79        21         13         19
                    3               80        20         16         17
                    4               79        21         16         17
...                                ...       ...        ...        ...
흑석시장    호프-간이주점     3               59        41         12         10
                    4               69        31          9         14
        회계사사무소      1               72        28          5         22
                    2               92         8         24         15
                    3               97         4         11         23

                              수요일_매출_비율  목요일_매출_비율  ...  시간대_건수~24_매출_건수  \
상권_코드_명 서비스_업종_코드_명 기준_분기_코드                        ...
가락시장    미곡판매        4                19         14  ...             3751
        반찬가게        1                14         15  ...            31865
                    2                16         14  ...            17010
                    3                17         16  ...            13780
                    4                15         15  ...           300350
...                                 ...        ...  ...              ...
흑석시장    호프-간이주점     3                 8         13  ...             2654
                    4                13         15  ...             4757
        회계사사무소      1                13         13  ...               48
                    2                11         26  ...               31
                    3                20         36  ...               15

                              남성_매출_건수  여성_매출_건수  연령대_10_매출_건수  연령대_20_매출_건수  \
상권_코드_명 서비스_업종_코드_명 기준_분기_코드
가락시장    미곡판매        4           124915    113662             0          3375
        반찬가게        1           151575     99255             0          9474
                    2            81816     72988           431          5168
                    3            91720     82247             0          8181
                    4          2011807   1569572          5382        347502
...                                ...       ...           ...           ...
흑석시장    호프-간이주점     3             2690      1490             7           863
                    4             5178      3025            36          2725
        회계사사무소      1               78        47             0            43
                    2               62        42             0            36
                    3               56        89             0            26

                              연령대_30_매출_건수  연령대_40_매출_건수  연령대_50_매출_건수  \
상권_코드_명 서비스_업종_코드_명 기준_분기_코드
가락시장    미곡판매        4                20631         66397        105034
        반찬가게        1                35956         70404         79018
                    2                21961         27129         48659
                    3                29711         33587         55333
                    4               759380        883180        896745
...                                    ...           ...           ...
흑석시장    호프-간이주점     3                  915          1038          1096
                    4                 1632          1745          1694
        회계사사무소      1                   20            25            26
                    2                   15            16            20
                    3                   16            26            63

                              연령대_60_이상_매출_건수  점포수
상권_코드_명 서비스_업종_코드_명 기준_분기_코드
가락시장    미곡판매        4                   43140    5
        반찬가게        1                   55980    5
                    2                   51457    5
                    3                   47151    5
                    4                  689191    6
...                                       ...  ...
흑석시장    호프-간이주점     3                     266   11
                    4                     369   11
        회계사사무소      1                      10    1
                    2                      16    1
                    3                      15    1

[177230 rows x 74 columns]

In [8]:
seoul_sales_2019_1=seoul_sales_2019[seoul_sales_2019['기준_분기_코드']==1]
E_1=seoul_sales_2019_1.groupby(['상권_코드_명', '서비스_업종_코드_명'])
category_seoul_1=E_1.sum()
#category_seoul_1

In [9]:
seoul_sales_2019_2=seoul_sales_2019[seoul_sales_2019['기준_분기_코드']==2]
E_2=seoul_sales_2019_2.groupby(['상권_코드_명', '서비스_업종_코드_명'])
category_seoul_2=E_2.sum()
#category_seoul_2

In [10]:
seoul_sales_2019_3=seoul_sales_2019[seoul_sales_2019['기준_분기_코드']==3]
E_3=seoul_sales_2019_3.groupby(['상권_코드_명', '서비스_업종_코드_명'])
category_seoul_3=E_3.sum()
#category_seoul_3

In [11]:
seoul_sales_2019_4=seoul_sales_2019[seoul_sales_2019['기준_분기_코드']==4]
E_4=seoul_sales_2019_4.groupby(['상권_코드_명', '서비스_업종_코드_명'])
category_seoul_4=E_4.sum()
#category_seoul_4

In [12]:
#for i in range(len(business_area)):
    for j in range(len(category_name)):
        try:
            plt.rcParams['figure.figsize']=[5,5]
            #area_2019_1=category_seoul_1.loc[business_area[i]].loc[category_name[j]]
            #area_2019_2=category_seoul_2.loc[business_area[i]].loc[category_name[j]]
            #area_2019_3=category_seoul_3.loc[business_area[i]].loc[category_name[j]]
            #area_2019_4=category_seoul_4.loc[business_area[i]].loc[category_name[j]]
            #print(business_area[i], category_name[j])
            #budget_data=[area_2019_1['당월_매출_금액'], area_2019_2['당월_매출_금액'], area_2019_3['당월_매출_금액'], area_2019_4['당월_매출_금액']]
            #budget_category=['2019_1/4 USE_AMOUNT', '2019_2/4 USE_AMOUNT', '2019_3/4 USE_AMOUNT', '2019_4/4 USE_AMOUNT']
            colors=['red', 'yellow' , 'green', 'blue']
            #plt.pie(budget_data, labels=budget_category, autopct='%0.1f%%', colors=colors)
            #plt.show()
            plt.close()
        except:
            pass

IndentationError: unexpected indent (<ipython-input-12-d8cf5d877aa8>, line 2)

In [ ]:
#for i in range(len(business_area)):
    for j in range(len(category_name)):
        try:
            plt.rcParams['figure.figsize']=[5,5]
            #area_2019_1=category_seoul_1.loc[business_area[i]].loc[category_name[j]]
            #area_2019_2=category_seoul_2.loc[business_area[i]].loc[category_name[j]]
            #area_2019_3=category_seoul_3.loc[business_area[i]].loc[category_name[j]]
            #area_2019_4=category_seoul_4.loc[business_area[i]].loc[category_name[j]]
            #print(business_area[i], category_name[j])
            #budget_data=[area_2019_1['당월_매출_건수'], area_2019_2['당월_매출_건수'], area_2019_3['당월_매출_건수'], area_2019_4['당월_매출_건수']]
            #budget_category=['2019_1/4 USE_COUNT', '2019_2/4 USE_COUNT', '2019_3/4 USE_COUNT', '2019_4/4 USE_COUNT']
            colors=['pink', 'orange' , 'lightgreen', 'lightskyblue']
            #plt.pie(budget_data, labels=budget_category, autopct='%0.1f%%', colors=colors)
            #plt.show()
            plt.close()
        except:
            pass